services:
  user-service:
    environment:
      - NODE_ENV=test

  event-service:
    environment:
      - NODE_ENV=test

  registration-service:
    environment:
      - NODE_ENV=test

  notification-service:
    environment:
      - NODE_ENV=test

  frontend:
    environment:
      - APP_ENV=test
