apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: event-management

resources:
  - namespace.yaml
  - config.yaml
  - postgres.yaml
  - messaging.yaml
  - backend-services.yaml
  - frontend.yaml
  - monitoring.yaml
